<a href="https://colab.research.google.com/github/gembuspol/uczenieMaszynowe/blob/main/cwiczenia1_rozdzial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.models import Sequential
from keras.layers import *
import numpy as np

m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(12,input_dim=2, activation='tanh'))
#m.add(Activation('tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[0],[1],[1],[0]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))


[[0.45678547]
 [0.5703495 ]
 [0.48452982]
 [0.5445105 ]]


In [8]:
from keras.models import Sequential
from keras.layers import *
import numpy as np

m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(12,input_dim=2, activation='tanh'))
#m.add(Activation('tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[0],[1],[1],[0]],'float32')
Yand=np.array([[0],[0],[0],[1]],'float32')
Yor=np.array([[0],[1],[1],[1]],'float32')
Ynor=np.array([[1],[0],[0],[0]],'float32')
Ynand=np.array([[1],[1],[1],[1]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))
print("Bramka AND")
m.fit(X,Yand,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

print("Bramka OR")
m.fit(X,Yor,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

print("Bramka NOR")
m.fit(X,Ynor,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

print("Bramka NAND")
m.fit(X,Ynand,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

[[0.44755563]
 [0.39121032]
 [0.62760067]
 [0.43180683]]
Bramka AND
[[0.09460354]
 [0.43889853]
 [0.14334106]
 [0.48463395]]
Bramka OR
[[0.13130897]
 [0.9322041 ]
 [0.9228915 ]
 [0.98695743]]
Bramka NOR
[[0.34774584]
 [0.12802032]
 [0.3499901 ]
 [0.12894657]]
Bramka NAND
[[0.9652982 ]
 [0.97563803]
 [0.9330058 ]
 [0.9737195 ]]


In [2]:
from keras.models import Sequential
from keras.layers import *
import numpy as np

m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(20,input_dim=16, activation='tanh'))
m.add(Dense(30,input_dim=8, activation='tanh'))
#m.add(Activation('tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[0],[1],[1],[0]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

[[0.41237065]
 [0.6344195 ]
 [0.5575907 ]
 [0.21433195]]


In [3]:
#zmiana ilosci warstw i neuronów
#from keras.models import Sequential
from keras.layers import *
import numpy as np

m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(20,input_dim=16, activation='tanh'))
m.add(Dense(30,input_dim=8, activation='tanh'))
#m.add(Activation('tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[0],[1],[1],[0]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

[[0.14069033]
 [0.87183774]
 [0.44589457]
 [0.56860715]]


In [6]:
#zmiana ilosci warstw i neuronów
#from keras.models import Sequential
from keras.layers import *
import numpy as np

m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(20,input_dim=16, activation='tanh'))
m.add(Dense(30,input_dim=8, activation='tanh'))
#m.add(Activation('tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[0],[1],[1],[0]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))
#rózne optymalizatroy
m.compile(optimizer='adadelta',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
result=m.evaluate(X,Y)
print(m.predict(X))
m.compile(optimizer='ftrl',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
result=m.evaluate(X,Y)
print(m.predict(X))

[[0.31034708]
 [0.44509336]
 [0.70625484]
 [0.5684235 ]]
1/1 [==============================] - 0s 82ms/step - loss: 0.5921
[[0.30991298]
 [0.4449134 ]
 [0.7066237 ]
 [0.5683977 ]]
1/1 [==============================] - 0s 81ms/step - loss: 0.6931
[[0.49899638]
 [0.49899638]
 [0.49899656]
 [0.49899656]]


In [7]:
#zmiana ilosci warstw i neuronów
#from keras.models import Sequential
from keras.layers import *
import numpy as np

m = Sequential()
m.add(Dense(20,input_dim=2, activation='tanh'))
m.add(Dense(20,input_dim=16, activation='tanh'))
m.add(Dense(30,input_dim=8, activation='tanh'))
m.add(Dense(10,input_dim=8, activation='tanh'))
m.add(Dense(32,input_dim=8, activation='tanh'))
#m.add(Activation('tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[0],[1],[1],[0]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))
#rózne optymalizatroy
m.compile(optimizer='adadelta',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
result=m.evaluate(X,Y)
print(m.predict(X))
m.compile(optimizer='ftrl',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
result=m.evaluate(X,Y)
print(m.predict(X))

[[0.00418374]
 [0.99425423]
 [0.9938221 ]
 [0.01718426]]
1/1 [==============================] - 0s 95ms/step - loss: 0.0082
[[0.00404486]
 [0.9944291 ]
 [0.99399376]
 [0.01686704]]


1/1 [==============================] - 0s 113ms/step - loss: 0.6931
[[0.5001493]
 [0.5001493]
 [0.5001493]
 [0.5001493]]
